# Generated by Django 3.2.13 on 2022-05-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprequire',
            name='update_user',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='最近更新'),
        ),
    ]
