# Generated by Django 3.2.13 on 2022-05-06 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0002_alter_apprequire_update_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprequire',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tracer.project', verbose_name='项目'),
        ),
    ]
