# Generated by Django 3.2.9 on 2022-02-28 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0003_wiki'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiki',
            name='last_edit_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近修改时间'),
        ),
        migrations.AddField(
            model_name='wiki',
            name='last_edit_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edit_user', to=settings.AUTH_USER_MODEL, verbose_name='最近修改人'),
        ),
        migrations.CreateModel(
            name='WikiJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.BooleanField(default=False, verbose_name='收藏')),
                ('editor', models.BooleanField(default=False, verbose_name='编辑')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='参与者')),
                ('wiki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracer.wiki', verbose_name='wiki')),
            ],
        ),
    ]
