# Generated by Django 3.2.13 on 2022-05-06 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0004_alter_apprequire_project'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apprequire',
            unique_together={('id', 'title')},
        ),
    ]
