# Generated by Django 3.2.9 on 2022-03-02 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0004_auto_20220228_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bucket',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='cos桶'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='region',
            field=models.CharField(default=django.utils.timezone.now, max_length=32, verbose_name='cos区域'),
            preserve_default=False,
        ),
    ]
