# Generated by Django 3.2.9 on 2022-03-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0005_auto_20220302_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokAutoTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=32, verbose_name='平台')),
                ('version_detail', models.CharField(max_length=32, verbose_name='版本详情')),
                ('task_id', models.IntegerField(max_length=16, verbose_name='任务id')),
                ('test_path', models.CharField(max_length=300, verbose_name='脚本路径')),
                ('event', models.CharField(max_length=16, verbose_name='EVENT')),
                ('test_case_url', models.CharField(max_length=300, verbose_name='埋点url')),
                ('result', models.BooleanField(default=False, verbose_name='测试结果')),
            ],
        ),
    ]
