# Generated by Django 3.2.13 on 2022-05-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0005_alter_apprequire_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprequire',
            name='title',
            field=models.CharField(max_length=32, unique=True, verbose_name='需求名称'),
        ),
        migrations.AlterUniqueTogether(
            name='apprequire',
            unique_together=set(),
        ),
    ]
