# Generated by Django 3.2.9 on 2022-03-03 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0006_tiktokautotest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tiktokautotest',
            unique_together={('task_id', 'test_case_url')},
        ),
    ]
