# Generated by Django 3.2.9 on 2022-03-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0007_alter_tiktokautotest_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokautotest',
            name='task_id',
            field=models.IntegerField(verbose_name='任务id'),
        ),
    ]
