# Generated by Django 3.2.13 on 2022-05-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0007_developerdebug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.SmallIntegerField(choices=[(0, 'Android'), (1, 'iOS')], default=0, verbose_name='平台')),
                ('scene_id', models.CharField(max_length=16, verbose_name='场景id')),
                ('test_path', models.CharField(max_length=248, verbose_name='脚本路径')),
                ('scene_path', models.CharField(blank=True, max_length=124, null=True, verbose_name='场景路径')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
