# Generated by Django 3.2.9 on 2022-03-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0009_filerepository'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokautotest',
            name='create_time',
            field=models.DateTimeField(default=None, verbose_name='收录时间'),
        ),
    ]
