# Generated by Django 3.2.9 on 2022-03-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0010_tiktokautotest_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokautotest',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='收录时间'),
        ),
    ]
