# Generated by Django 3.2.9 on 2022-03-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0011_alter_tiktokautotest_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokautotest',
            name='test_path',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='脚本路径'),
        ),
    ]
