# Generated by Django 3.2.9 on 2022-03-11 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0012_alter_tiktokautotest_test_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokautotest',
            name='project',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='tracer.project', verbose_name='项目'),
        ),
    ]
