# Generated by Django 3.2.9 on 2022-03-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0015_alter_tiktokautotest_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokautotest',
            name='platform',
            field=models.CharField(max_length=32, verbose_name='平台'),
        ),
    ]
