# Generated by Django 3.2.9 on 2022-03-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0016_alter_tiktokautotest_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokautotest',
            name='platform',
            field=models.SmallIntegerField(choices=[(1, 'Android'), (2, 'IOS')], verbose_name='平台'),
        ),
    ]
