# Generated by Django 3.2.9 on 2022-03-22 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0019_issuesreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprequire',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tracer.project', verbose_name='项目'),
        ),
    ]
