# Generated by Django 3.2.9 on 2022-03-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0021_projectinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokautotest',
            name='case_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='case_id'),
        ),
        migrations.AlterUniqueTogether(
            name='tiktokautotest',
            unique_together={('task_id', 'case_id')},
        ),
    ]
