# Generated by Django 3.2.9 on 2022-03-31 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0022_auto_20220327_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokautotest',
            name='version_detail',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='版本详情'),
        ),
    ]
