# Generated by Django 3.2.9 on 2022-04-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0023_alter_tiktokautotest_version_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerepository',
            name='name',
            field=models.CharField(help_text='文件/文件夹名', max_length=120, verbose_name='文件夹名称'),
        ),
    ]
