# Generated by Django 3.2.9 on 2022-04-12 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0024_alter_filerepository_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiktokautotest',
            options={'ordering': ('-id', '-create_time')},
        ),
        migrations.AlterIndexTogether(
            name='tiktokautotest',
            index_together={('id', 'create_time')},
        ),
    ]
