# Generated by Django 3.2.9 on 2021-12-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_articleupdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default='...', verbose_name='内容'),
        ),
    ]
