# Generated by Django 3.2.9 on 2022-01-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='comment_coount',
            new_name='comment_count',
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(),
        ),
    ]
