# Generated by Django 3.2.9 on 2022-04-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('sex', models.SmallIntegerField(choices=[(0, '男'), (1, '女')], verbose_name='性别')),
                ('age', models.PositiveIntegerField(verbose_name='年龄')),
                ('classmate', models.CharField(max_length=12, verbose_name='班级')),
                ('discription', models.TextField(blank=True, max_length=32, null=True, verbose_name='个性签名')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'ordering': ('id', '-create_at'),
                'index_together': {('id', 'create_at')},
            },
        ),
    ]
